###############################
# SERVER HTTPS (PORTA 443)
###############################

server {
    listen 443 ssl;                      # Escuta na porta 443 (HTTPS) em IPv4
    listen [::]:443 ssl;                 # Escuta na porta 443 (HTTPS) em IPv6

    server_name raamorim.42.fr;          # Nome do domínio que este servidor responde

    ssl_protocols TLSv1.2 TLSv1.3;       # Protocolos SSL/TLS permitidos

    ssl_certificate /etc/nginx/ssl/nginx.cert;         # Caminho para o certificado SSL
    ssl_certificate_key /etc/nginx/ssl/nginx.key;      # Caminho para a chave privada SSL

    # Diretório onde ficam os ficheiros a servir
    root /var/www/html/;                 # Ex: pedido a /wp-admin → nginx procura /var/www/html/wp-admin

    index index.php;                     # Ficheiro padrão a servir quando acedem a uma pasta

    ###############################
    # LOCALIZAÇÃO PRINCIPAL "/"
    ###############################
    location / {
        # Ordem de tentativa:
        # 1. O ficheiro tal como no URL ($uri)
        # 2. O diretório correspondente ($uri/)
        # 3. Se nada existir → enviar pedido para index.php
        try_files $uri $uri/ /index.php?$args;
    }

    ###############################
    # PROCESSAMENTO DE FICHEIROS PHP
    ###############################
    location ~ \.php$ {
        include fastcgi_params;          # Carrega variáveis obrigatórias para php-fpm funcionar (ex: QUERY_STRING)

        fastcgi_pass wordpress:9000;     # Envia ficheiros PHP para o serviço php-fpm dentro do container "wordpress"

        # Indica o caminho absoluto do ficheiro PHP que deve ser executado
        # SCRIPT_FILENAME = document_root + script_name
        # Exemplo:
        #   /var/www/html  +  /wp-login.php
        #   → /var/www/html/wp-login.php
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}


###############################
# SERVER HTTP (PORTA 80)
# FAZ REDIRECIONAMENTO PARA HTTPS
###############################

server {
    listen 80;                           # Escuta na porta 80 (HTTP) em IPv4
    listen [::]:80;                      # Escuta na porta 80 (HTTP) em IPv6

    server_name raamorim.42.fr;          # Domínio associado

    # Redirecionamento permanente (301) para HTTPS
    # $host → domínio pedido pelo cliente
    # $request_uri → caminho + query string
    # Exemplo: /blog/artigo?id=10
    return 301 https://$host$request_uri;
}
