server {
	listen 443 ssl; #ipv4
	listen [::]:443 ssl; #ipv6

	server_name raamorim.42.fr; #domain do server
	ssl_protocols TLSv1.2 TLSv1.3; #ssl protocols aceites

	ssl_certificate /etc/nginx/ssl/nginx.cert; #path do certificado ssl
	ssl_certificate_key /etc/nginx/ssl/nginx.key; #path da key do certificado ssl

	#define onde estao os ficheiros
	
	root /var/www/html/; #define onde nginx deve procurar os ficheiros, caso passem wp-admin, vai
			     #procurar em /var/www/html/wp-admin
	index index.php; #define qual o ficheiro padrao a servir quando acedem a uma pasta, se pedirem 
	                 #"/" (homepage") nginx tenta carregar /var/www/html/index.php

	location / {
		try_files $uri $uri/ /index.php?$args;
	}
	#critico para o wordpress, se n tiver erro 404 nor found vao existir em links como /como, /blog/	artigo-1;
	#$uri tenta servir o ficheiro exatamente como esta o URL, $uri/ se nao encontrar o ficheiro 
	#tenta como diretorio
	#/index.php?$args -> se nada existir envia a requisicao para index.php	
	#sempre que alguem pedir um ficheiro que acabe em .php, aplica estas regras
	location ~ \.php$ {
		include fastcgi_params; #importa um conjunto de variaveis padrao que o php-fom precisa 
		                        #para interpretar pedidos. ex: QUERY_STRING, sem isto php-fpm 
					#nao funciona corretamente
		fastcgi_pass wordpress:9000; #passa o ficheiro php para o wordpress na porta 9000
					     #o container wordpress executa php-fpm, php-fpm escuta na
	       				     #porta 9000
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name; # diz q o ficheiro php 		#que precisamos de executar esta neste complete path. este caminho e formado juntanto 2 		#variaveis : 
		#$document_root, uma variavel que contem o diretorio root definido no nginx.
		#fastcgi_script_name, uma variavel que contem o caminho do ficheiro php pedido no URL, 
		#este script vai variando confirme a pagina php que o user pede, se pedir /wp-login.php, 		#o script vai ter esse valor;
		#Qd juntamos as 2 no exemplo passado fica: /var/www/html/wp-login.php. se nao encontrar a pagina retorna um erro. sem estas linhas os ficheiros php n sao encontrados, wp nao instala, wp-admin nao funciona.
	}
}

server {
    listen 80; #ouve na porta 80, porta do http nao segura, ipv4
    listen [::]: 80; #ipv6
    server_name raamorim.42.fr; #dominio 
    return 301 https://$host$request_uri; #redireciona http->https, devolve um codigo 301, constroi a nova url mantedo caminhos e parametros
    #variaveis: $host : domnio pedido peli user, raamorim.42.fr; $request_uri -> caminho + query string. ex: /blog/artigo?id=10
}


